import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ProviderLayout from "@/components/layouts/ProviderLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} text-[#EAECEF] bg-[#181E25]`}>
                <ProviderLayout>{children}</ProviderLayout>
            </body>
        </html>
    );
}
